apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Reference the base k8s folder from your app source repository
resources:
- github.com/kmssankar/expressappdbm/k8s?ref=main # or a specific tag/branch
# Kargo will modify the newTag fields in this block
images:
- name: ghcr.io/kmssankar/expressappdbm
  newTag: 75b9f4f312ade06adfd695e43424dae3b19a435a
- name: ghcr.io/kmssankar/flyway-migrations
  newTag: cac29cc5bd8cfc8354fb10ad0b50da2153920b08
