apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "../../base" # or wherever your base manifests are located

images:
  - name: ghcr.io/kmssankar/expressappdbm
    newTag: placeholder
  - name: ghcr.io/kmssankar/flyway-migrations
    newTag: placeholder